# 文章の書き方 {#howtowrite}

世の中には，**文章がうまい人**と**話がうまい人**がいる。
しかし，**文章も話もうまい人**はいない（仮説）。

## 文章がうまくなるコツ

とにかくたくさん書く。

楽器がうまくなりたい人，スポーツがうまくなりたい人は何をすべきだろうか？
まず，ひたすら練習を繰り返すことであろう。

1. 思いつくまま書く。
1. 構造化する。
1. 不要な文章を削除する。


### 思いつくまま書く

とにかく，何でも書く。
頭の中にある事柄，思いついた文章等，何でも文字として表現する。
この段階では，不完全な文章でも，単語だけであっても構わない。

これらは，文章を書くための材料になる。
これらがなければ，文章を書くことはできない。


### 構造化する

書いた文字を，並べ替え，文章の流れをつくる。
節をつくり，節の中に段落をつくる。

最初から完成形を目指す必要はない。
「創造的破壊」の過程である。


### 不要な文章を削除する

重複した文章があれば，削除する。
経験的には，3分の1くらいの文字数に減ることになる。
この段階で文字数が減ることを見越して，最初にたくさん書いておくことが重要である。

段落ごとに，その段落で何を言いたいのかを明らかにする。
その段落に必要のない文章だけれど，削除するのは忍びない文章があることもあるだろう。
そうった文章の待避場所として，「メモ」という節を設け，そこに移動させておくとよい。


## フォーマット

最初は，フォーマットを無視して書く。

リッチテキストで書くと，文章の「内容」と「見た目」の両方を同時に意識しなければならない。
集中力が途切れる。

プレーンテキストで書くべきである。
プレーンテキストで書くと，フォント情報を考えなくてよい。


## マークダウン

プレーンテキストで書くときに便利なフォーマットがマークダウンである。
強調したければ，2つのアスタリスクで左右を挟むだけでよい。
最初にルールを覚える必要がある。
ただし，覚えるルールは限られている。

段落は空の行を作る。
通常の段落と違うため，

## フォーマットを整える

最後に，見た目を綺麗にする。
最後とは，他人に見せるときである。
途中経過を他人に見てもらいたいときは，未完成の状態で見た目を綺麗にする必要がある。

LaTeXが便利である。
ただし，ハードルが高いかもしれない。

### 図や表にはキャプションをつける

図のキャプションは，図の下につける。
表のキャプションは，表の上につける。
ゴシック体にするなど，本文のフォントと違うフォントを使うとわかりやすい。

