# 文章の書き方 {#howtowrite}

世の中には，**書くことが得意な人**と**話すことが得意な人**が世の中にいる。
しかし，**両方得意な人**はいない（仮説）。

話すことが得意な人は，人を惹きつける能力に長けている。
そこでは，論理性よりも聴衆の興味にいかに刺激するかが問われ，あるセンテンスと次のセンテンスの間に論理的な繋がりがある必要はなく，。


## 文章がうまくなるコツ

とにかくたくさん書く。

楽器がうまくなりたい人，スポーツがうまくなりたい人は，まず何をすべきか考えてみよう。

ルールを覚えることだろうか？

ルールを覚えることは確かに重要である。
例えば，テニスをやろうとすると，テニスのルールを覚えなければならない。
サーバーはどこからサーブしなければならないのか，どうすれば自分に点が入るのか，どういった行動をとると反則になるのか。
こうしたことはルールで定められている。
しかし，いくらテニスのルールを覚えたとしても，テニスが上手くなるわけではない。

テニスが上手くなりたければ，まずは，ラケットとボールを手に入れる必要がある。
これらを自分のために買うのもいいが，借りられるのであれば，他人やレンタルショップから借りても問題ない。
とくに続ける自信がなかったり，お金がない場合は，借りた方がいいだろう。

ラケットとボールを入手したら，今度は，ひたすら素振りをする必要がある。
素振りだけではなく，走ったり，○○したり，テニスとは直接関係のないことをする時間もとらなければならない。
こうしたことを一般的な言葉で表現すると，練習と呼ぶ。
何かの能力を身に付けたければ，練習を繰り返すことが重要である。
文章を書く場合も同様である。

文章が美味くなりたければ，段落冒頭の字下げや引用といったルールを覚える必要がある。
しかし，こうしたルールを知ったからといって文章がうまくなることは，ほぼあり得ない。
文章を書く練習をしなければならない。

文章を書く練習としては，以下の3つの段階を踏み，これらを繰り返すことが望ましい。
1. 思いつくまま書く。
1. 構造化する。
1. 不要な文章を削除する。


### 思いつくまま書く

とにかく，何でも書く。
頭の中にある事柄，思いついた文章等，何でも文字として表現する。
この段階では，不完全な文章でも，単語だけであっても構わない。

これらは，文章を書くための材料になる。
これらがなければ，文章を書くことはできない。


### 構造化する

書いた文字を，並べ替え，文章の流れをつくる。
節をつくり，節の中に段落をつくる。

最初から完成形を目指す必要はない。
「創造的破壊」の過程である。


### 不要な文章を削除する

重複した文章があれば，削除する。
経験的には，3分の1くらいの文字数に減ることになる。
この段階で文字数が減ることを見越して，最初にたくさん書いておくことが重要である。

段落ごとに，その段落で何を言いたいのかを明らかにする。
その段落に必要のない文章だけれど，削除するのは忍びない文章があることもあるだろう。
そうった文章の待避場所として，「メモ」という節を設け，そこに移動させておくとよい。


## フォーマット

最初は，フォーマットを無視して書く。

リッチテキストで書くと，文章の「内容」と「見た目」の両方を同時に意識しなければならない。
集中力が途切れる。

プレーンテキストで書くべきである。
プレーンテキストで書くと，フォント情報を考えなくてよい。


## マークダウン

プレーンテキストで書くときに便利なフォーマットがマークダウンである。
強調したければ，2つのアスタリスクで左右を挟むだけでよい。
最初にルールを覚える必要がある。
ただし，覚えるルールは限られている。

段落は空の行を作る。
通常の段落と違うため，

## フォーマットを整える

最後に，見た目を綺麗にする。
最後とは，他人に見せるときである。
途中経過を他人に見てもらいたいときは，未完成の状態で見た目を綺麗にする必要がある。

LaTeXが便利である。
ただし，ハードルが高いかもしれない。

### 図や表にはキャプションをつける

図のキャプションは，図の下につける。
表のキャプションは，表の上につける。
ゴシック体にするなど，本文のフォントと違うフォントを使うとわかりやすい。



[Seven simple, actionable suggestions that will make your papers better（あなたの論文がよくなる単純ですぐにできる7つの提案）](https://www.microsoft.com/en-us/research/wp-content/uploads/2016/07/How-to-write-a-great-research-paper.pdf)

