# やりがちな間違い {#mistake}

世の中には，**文章がうまい人**と**話がうまい人**がいる。
しかし，**文章も話もうまい人**はいない（仮説）。

どういう文章が間違っているのか。
どういう文章が修正すべきなのか。

どういう修正が必要なのか。


## 構成・外観

### 無意味な改行などをして，ページ数を稼ごうとしない。

レポートが長ければいいというわけではない。

指定された文字数に満たない場合の小細工は見苦しい。


### 段落の先頭は1字下げる

段落の先頭を1字下げる。

半角スペースや全角スペースで1字下げるのではなく，インデントの機能を使って下げる。


## 半角・全角を揃える

文中に記す括弧は半角ではなく，全角を使う。例：()ではなく，（）を使う。

数字は基本的に半角を用いる。

1桁の場合は全角，2桁の場合は半角とする流儀もある。
このルールはパソコンが主流ではない時代のワープロの場合に，都合がよかった。
しかし，適切に字詰めされる現代において，こうしたルールに従うメリットはない。

また，数字は読みやすくするために，下から3桁ずつコンマを付ける。


### 段落に意味を持たせる

話題が変わるときには，段落を変える。同じ段落の中に複数の異なる話題を含めないようにする。


## 言い回し

### 文末をである調にする

学生のレポートを読むと，文末を「だ」としている場合が散見される。
文末は「だ」よりも「である」とする方がよい。

また，接続詞として「だが」を用いるよりも，いったんそこで文章を区切って，「…。しかし，…」とする方がよい。
同様に，接続詞として「だから」を用いるよりも，「このため」や「したがって」を用いる方がよい。


### 体言止めはできるだけ使わない

体言止めはできるだけ使わないようにする。

体言止めの文章は，肯定文か否定文なのかわからない。

体言止めを使うと効果的な文章になることは確かにある。
自信があるときにのみ，意図的に体言止めを使うのならよい。


### 句読点を意識して使う

一文が長すぎる場合がよくある。
適切に句点を追加する。
また，文章を分割して，一文をできるだけ短くする。


## 過去形と現在形

過去形と現在形を意識して使い分ける。


## 表現

### 接続詞「が」はできるだけ使わない

自分の書いた文章の中に，接続詞「が」が出てきた場合，意識して別の言葉で言い換える。

接続詞の「が」は多様な意味を持つ。
順接の場合は，「が」を削除した方がよい。
逆説の場合は，「しかし」などと言い換えることができる。
どうしても言い換えることが難しいときもあるが，読者を混乱させるため，仕様を控えた方がよい。


### 何々をしている

「何々（名詞）をしている」は，「何々している（動詞）」に置き換えることができかどうか検討すべきである。

「出荷をしている」→「出荷している」

「調整をしている」→「調整している」


### 代名詞が何を指すかわかりやすいか要検討

「その」が何を指すかわかりにくい場合，名詞を書く。
とくに，段落が変わったりして，対応する名詞が離れてしまう場合は，代名詞を使わない方がよい。

「その対策」→「獣害対策」


### 程度を表す副詞はできるだけ使わない

「とても」「非常に」「強く」といった副詞をできるだけ使わないようにする。
レポートや論文において，感情表現をする必要はない。

また，「AはBより大きい」ときに，「AはBより非常に大きい」とした場合の「非常に」にどのような意味があるのか考えてほしい。
福祉を削除しても意味が変わらないのであれば，削除した方がよい。
